# Generated by Django 3.0.5 on 2020-07-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile',
            field=models.CharField(default='+91-0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
