# Generated by Django 3.0.5 on 2020-04-21 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userin', '0002_lookingcab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookingcab',
            name='datetime',
        ),
        migrations.AddField(
            model_name='lookingcab',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
