# Generated by Django 3.0.5 on 2020-04-25 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userin', '0004_auto_20200421_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=50)),
                ('dest', models.CharField(max_length=50)),
            ],
        ),
    ]
