# Generated by Django 3.0.5 on 2020-04-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userin', '0005_bookedcab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcab',
            name='dest',
            field=models.CharField(choices=[('1', 'IITG_Campus'), ('2', 'Guwahati Airport'), ('3', 'GHY RLY Station'), ('4', 'Kamakhya Junction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='source',
            field=models.CharField(choices=[('1', 'IITG_Campus'), ('2', 'Guwahati Airport'), ('3', 'GHY RLY Station'), ('4', 'Kamakhya Junction')], max_length=50),
        ),
    ]
